cantidadDeDolares:int=int(input("Cantidad de dolares: "))
precioPorDolar:int=float(input("Pesos por dolar: "))
print(f"La cantidad de dolares es: {cantidadDeDolares} Y el dolar esta en: {precioPorDolar}")
print("Recibiras: ")
print(cantidadDeDolares*precioPorDolar)